# Increase the maximum heap size for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED

# Use AndroidX and enable Jetifier for compatibility
android.useAndroidX=true
android.enableJetifier=true

# Enable parallel project execution (optional)
org.gradle.parallel=true

# Other Gradle settings can go here
